// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Generated on: 2025-06-05T11:09:23.574883

import 'package:rdf_mapper/mapper.dart';
import 'package:rdf_mapper_generator/test/fixtures/annotation_test_models.rdf_mapper.g.dart';
import 'package:rdf_mapper_generator/test/fixtures/global_resource_processor_test_models.rdf_mapper.g.dart';

/// Initializes and returns an RdfMapper with test mappers registered.
RdfMapper initTestRdfMapper({RdfMapper? rdfMapper}) {
  if (rdfMapper == null) {
    rdfMapper = RdfMapper.withDefaultRegistry();
  }
  var registry = rdfMapper.registry;

  registry.registerMapper<Book>(BookMapper());
  registry.registerMapper<BookWithMapperInstance>(BookWithMapperInstanceMapper());
  registry.registerMapper<BookWithMapper>(BookWithMapperMapper());
  registry.registerMapper<BookWithTemplate>(BookWithTemplateMapper());
  registry.registerMapper<ClassWithEmptyIriStrategy>(ClassWithEmptyIriStrategyMapper());
  registry.registerMapper<ClassWithEmptyIriStrategyNoRegisterGlobally>(ClassWithEmptyIriStrategyNoRegisterGloballyMapper());
  registry.registerMapper<ClassWithIriMapperInstanceStrategy>(ClassWithIriMapperInstanceStrategyMapper());
  registry.registerMapper<ClassWithIriMapperStrategy>(ClassWithIriMapperStrategyMapper());
  registry.registerMapper<ClassWithIriNamedMapperStrategy>(ClassWithIriNamedMapperStrategyMapper());
  registry.registerMapper<ClassWithIriTemplateAndContextVariableStrategy>(ClassWithIriTemplateAndContextVariableStrategyMapper());
  registry.registerMapper<ClassWithIriTemplateStrategy>(ClassWithIriTemplateStrategyMapper());
  
  return rdfMapper;
}
