name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  rdf_core: ^0.9.3
  rdf_mapper: ^0.8.6
  rdf_mapper_annotations: ^0.2.3
  rdf_vocabularies: ^0.3.0

dev_dependencies:
  build_runner: ^2.5.4
  lints: ^5.0.0
  rdf_mapper_generator: 
    path: ../
  test: ^1.24.0
