targets:
  $default:
    builders:
      rdf_mapper_generator|rdf_mapper_generator:
        generate_for:
          - lib/**.dart
          - test/**.dart
builders:
  rdf_mapper_generator:
    import: 'package:rdf_mapper_generator/builder.dart'
    builder_factories: ['rdfMapperBuilder']
    build_extensions: { '.dart': ['.rdf_mapper.g.dart'] }
    build_to: source
    auto_apply: dependents
