name: rdf_mapper_generator
version: 0.3.0-dev
homepage: https://kkalass.github.io/rdf_mapper_generator/
repository: https://github.com/kkalass/rdf_mapper_generator
issue_tracker: https://github.com/kkalass/rdf_mapper_generator/issues
documentation: https://kkalass.github.io/rdf_mapper_generator/
topics:
  - rdf
  - orm
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kalaß <habbatical@gmail.com>"
description: Generate type-safe RDF mappers from annotated Dart classes.

environment:
  sdk: '^3.6.0'
  
dependencies:
  analyzer: '>=6.9.0 <8.0.0' 
  build: '>=2.5.3 <4.0.0'
  dart_style: '>=2.3.7'
  logging: '>=1.2.0'
  mustache_template: '>=2.0.0'
  rdf_core: ^0.9.3
  rdf_mapper_annotations: 
    path: ../rdf_mapper_annotations
  rdf_vocabularies: ^0.3.0
  path: '>=1.9.0'
  rdf_mapper: 
    path: ../rdf_mapper
  glob: '>=2.0.0'
  uuid: '>=3.0.0'

dev_dependencies:
  build_runner: '>=2.5.3'
  build_test: '>=3.1.0'
  crypto: '>=3.0.0'
  lints: '>=0.1.0'
  test: '>=1.25.0'
  yaml: '>=3.0.0'
