name: rdf_mapper_generator
version: 0.1.0-dev
homepage: https://kkalass.github.io/rdf_mapper_generator/
repository: https://github.com/kkalass/rdf_mapper_generator
issue_tracker: https://github.com/kkalass/rdf_mapper_generator/issues
documentation: https://kkalass.github.io/rdf_mapper_generator/
topics:
  - rdf
  - orm
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kalaß <habbatical@gmail.com>"
description: >
  Generator for generating Mappers from rdf_mapper_annotations .

environment:
  sdk: '^3.6.0'
dependencies:
  rdf_core: ^0.9.2
  rdf_vocabularies: ^0.3.0 
  rdf_mapper: ^0.7.0
  logging: ^1.2.0

dev_dependencies:
  test: ^1.16.0
  build_runner: ^2.4.15
  mockito: ^5.4.6
  yaml: ^3.1.2
  path: ^1.8.0
  lints: ^5.1.1
