name: rdf_mapper_generator
version: 0.1.0-dev
homepage: https://kkalass.github.io/rdf_mapper_generator/
repository: https://github.com/kkalass/rdf_mapper_generator
issue_tracker: https://github.com/kkalass/rdf_mapper_generator/issues
documentation: https://kkalass.github.io/rdf_mapper_generator/
topics:
  - rdf
  - orm
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kalaß <habbatical@gmail.com>"
description: >
  Generator for generating Mappers from rdf_mapper_annotations .

environment:
  sdk: '^3.6.0'
dependencies:
  analyzer: ^7.4.5
  build: ^2.4.2
  logging: ^1.3.0
  rdf_core: ^0.9.2
  source_gen: ^2.0.0
  rdf_mapper_annotations: 
    path: ../rdf_mapper_annotations

dev_dependencies:
  build_runner: ^2.4.15
  build_test: ^2.2.3
  test: ^1.26.2
