import 'package:analyzer/dart/element/element2.dart';
import 'package:rdf_mapper_generator/src/processors/global_resource_processor.dart';
import 'package:rdf_mapper_generator/src/processors/libs_by_classname.dart';
import 'package:rdf_mapper_generator/src/templates/template_data_builder.dart';
import 'package:rdf_mapper_generator/src/templates/template_renderer.dart';
import 'package:build/build.dart';

class BuilderHelper {
  static final _templateRenderer = TemplateRenderer();

  /// Builds the header comment for generated files.
  String _buildFileHeader(String sourcePath) {
    return '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// This file was generated by the RDF Mapper Generator.
// Source: $sourcePath
// Generated on: ${DateTime.now().toIso8601String()}

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values

''';
  }

  Future<String?> _build(ClassElement2 classElement,
      LibsByClassName libsByClassName, AssetReader reader) async {
    final resourceInfo = GlobalResourceProcessor.processClass(
      classElement,
      libsByClassName: libsByClassName,
    );

    if (resourceInfo != null) {
      final templateData =
          TemplateDataBuilder.buildGlobalResourceMapper(resourceInfo);
      final mapperCode = await _templateRenderer.renderGlobalResourceMapper(
          templateData, reader);
      return mapperCode;
    }
    return null;
  }

  Future<String?> build(
      String sourcePath,
      Iterable<ClassElement2> classElements,
      LibsByClassName libsByClassName,
      AssetReader reader) async {
    final generatedCode = StringBuffer();
    var hasGeneratedCode = false;

    for (final classElement in classElements) {
      final mapperCode = await _build(classElement, libsByClassName, reader);
      if (mapperCode != null) {
        hasGeneratedCode = true;
        generatedCode.writeln(mapperCode);
        generatedCode.writeln();
      }
    }

    if (hasGeneratedCode) {
      return _buildFileHeader(sourcePath) + generatedCode.toString();
    }
    return null;
  }
}
