import 'dart:async';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/element/element2.dart';
import 'package:build/build.dart';
import 'package:rdf_mapper_generator/builder_helper.dart';
import 'package:rdf_mapper_generator/src/processors/libs_by_classname.dart';

Builder rdfMapperBuilder(BuilderOptions options) => RdfMapperBuilder();

/// Builder that processes RDF annotations and generates mapper classes using mustache templates.
///
/// This builder scans Dart files for classes annotated with @RdfGlobalResource and generates
/// corresponding mapper classes that handle serialization/deserialization between Dart objects
/// and RDF triples.
class RdfMapperBuilder implements Builder {
  static final _builderHelper = BuilderHelper();

  @override
  Future<void> build(BuildStep buildStep) async {
    // Only process .dart files, skip generated files
    if (!buildStep.inputId.path.endsWith('.dart') ||
        buildStep.inputId.path.contains('.g.dart') ||
        buildStep.inputId.path.contains('.rdf_mapper.g.dart')) {
      return;
    }

    try {
      final sourceContent = await buildStep.readAsString(buildStep.inputId);

      // Parse the source file using the analyzer
      final parseResult = parseString(
        content: sourceContent,
        path: buildStep.inputId.path,
      );

      if (parseResult.errors.isNotEmpty) {
        log.warning(
          'Parse errors in ${buildStep.inputId.path}: ${parseResult.errors}',
        );
        return;
      }

      // Get the library element for the parsed file
      final library = await _resolveLibrary(buildStep);
      if (library == null) {
        return;
      }

      final libsByClassName = LibsByClassName.create(library);

      final generatedCode = StringBuffer();
      var hasGeneratedCode = false;

      // Process all classes in the library
      for (final fragment in library.fragments) {
        for (final classFragment in fragment.classes2) {
          final mapperCode = await _builderHelper.build(
            classFragment.element,
            libsByClassName,
            buildStep,
          );
          if (mapperCode != null) {
            hasGeneratedCode = true;
            generatedCode.writeln(mapperCode);
            generatedCode.writeln();
          }
        }
      }

      // Only create output file if we generated code
      if (hasGeneratedCode) {
        final outputId =
            buildStep.inputId.changeExtension('.rdf_mapper.g.dart');
        final output =
            _buildFileHeader(buildStep.inputId.path) + generatedCode.toString();
        await buildStep.writeAsString(outputId, output);

        log.info('Generated RDF mapper for ${buildStep.inputId.path}');
      }
    } catch (e, stackTrace) {
      log.severe(
        'Error processing ${buildStep.inputId.path}: $e',
        e,
        stackTrace,
      );
      // Re-throw to ensure build fails on errors
      rethrow;
    }
  }

  /// Resolves the library for the current build step.
  Future<LibraryElement2?> _resolveLibrary(BuildStep buildStep) async {
    try {
      // For build system integration, we need to use the resolver
      final resolver = buildStep.resolver;
      final library = await resolver.libraryFor(buildStep.inputId);

      // The library element from build system is LibraryElement, cast to Element2
      return library as LibraryElement2;
    } catch (e) {
      log.warning(
          'Could not resolve library for ${buildStep.inputId.path}: $e');
      return null;
    }
  }

  /// Builds the header comment for generated files.
  String _buildFileHeader(String sourcePath) {
    return '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// This file was generated by the RDF Mapper Generator.
// Source: $sourcePath
// Generated on: ${DateTime.now().toIso8601String()}

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values

''';
  }

  @override
  Map<String, List<String>> get buildExtensions => {
        '.dart': ['.rdf_mapper.g.dart']
      };
}
