// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: test/fixtures/rdf_mapper_annotations/examples/document_example.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field

import 'package:rdf_core/rdf_core.dart';
import 'package:rdf_mapper/rdf_mapper.dart';

// Other imports
import 'document_example.dart';
import 'package:rdf_vocabularies_core/foaf.dart';
import 'package:rdf_vocabularies_core/pim.dart';
import 'package:rdf_vocabularies_core/solid.dart';

/// Generated mapper for [Document<T>] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `Document<T>`.
class DocumentMapper<T> implements GlobalResourceMapper<Document<T>> {
  final SerializationProvider<Document<T>, T>
  _primaryTopicSerializationProvider;

  /// Constructor
  const DocumentMapper({
    required SerializationProvider<Document<T>, T>
    primaryTopicSerializationProvider,
  }) : _primaryTopicSerializationProvider = primaryTopicSerializationProvider;

  @override
  IriTerm? get typeIri => FoafDocument.classIri;

  @override
  Document<T> fromRdfResource(IriTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);

    final documentIri = subject.iri;
    final T primaryTopic = reader.require(
      FoafDocument.primaryTopic,
      deserializer: _primaryTopicSerializationProvider.deserializer(
        subject,
        context,
      ),
    );
    final Uri maker = reader.require(FoafDocument.maker);

    // Get unmapped triples as the last reader operation for lossless mapping
    final RdfGraph unmapped = reader.getUnmapped<RdfGraph>();

    return Document<T>(
      documentIri: documentIri,
      primaryTopic: primaryTopic,
      maker: maker,
      unmapped: unmapped,
    );
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    Document<T> resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = IriTerm(resource.documentIri);

    return context
        .resourceBuilder(subject)
        .addValue(
          FoafDocument.primaryTopic,
          resource.primaryTopic,
          serializer: _primaryTopicSerializationProvider.serializer(
            resource,
            subject,
            context,
          ),
        )
        .addValue(FoafDocument.maker, resource.maker)
        .addUnmapped(resource.unmapped)
        .build();
  }
}

/// Generated mapper for [Person] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `Person`.
class PersonMapper implements GlobalResourceMapper<Person> {
  final String Function() _documentIriProvider;

  /// Constructor
  const PersonMapper({required String Function() documentIriProvider})
    : _documentIriProvider = documentIriProvider;

  @override
  IriTerm? get typeIri => FoafPerson.classIri;

  @override
  Person fromRdfResource(IriTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);

    final String name = reader.require(FoafPerson.name);
    final Uri preferencesFile = reader.require(FoafPerson.pimPreferencesFile);
    final Uri storage = reader.require(Pim.storage);
    final Uri account = reader.require(Solid.account);
    final Uri oidcIssuer = reader.require(Solid.oidcIssuer);
    final Uri privateTypeIndex = reader.require(Solid.privateTypeIndex);
    final Uri publicTypeIndex = reader.require(Solid.publicTypeIndex);

    // Get unmapped triples as the last reader operation for lossless mapping
    final RdfGraph other = reader.getUnmapped<RdfGraph>();

    return Person(
      name: name,
      preferencesFile: preferencesFile,
      storage: storage,
      account: account,
      oidcIssuer: oidcIssuer,
      privateTypeIndex: privateTypeIndex,
      publicTypeIndex: publicTypeIndex,
      other: other,
    );
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    Person resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = IriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(FoafPerson.name, resource.name)
        .addValue(FoafPerson.pimPreferencesFile, resource.preferencesFile)
        .addValue(Pim.storage, resource.storage)
        .addValue(Solid.account, resource.account)
        .addValue(Solid.oidcIssuer, resource.oidcIssuer)
        .addValue(Solid.privateTypeIndex, resource.privateTypeIndex)
        .addValue(Solid.publicTypeIndex, resource.publicTypeIndex)
        .addUnmapped(resource.other)
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(Person resource) {
    final documentIri = _documentIriProvider();
    return '${documentIri}#me';
  }
}
