import 'package:rdf_core/rdf_core.dart';
import 'package:rdf_mapper/rdf_mapper.dart';
import 'package:rdf_mapper_annotations/rdf_mapper_annotations.dart';
import 'package:rdf_vocabularies/schema.dart';

// -- Iri as Term --
// A class that demonstrates standard IRI construction with prefix/suffix
@RdfIri('urn:isbn:{value}')
class StandardIsbn {
  @RdfIriPart()
  final String value;

  StandardIsbn(this.value);

  // When serialized, this will become: urn:isbn:{value}
}

// A class that demonstrates complete IRI construction (using the value as-is)
@RdfIri()
class AbsoluteUri {
  @RdfIriPart()
  final String uri;

  AbsoluteUri(this.uri) {
    if (!uri.contains('://')) {
      throw ArgumentError('Not a valid absolute URI: $uri');
    }
  }

  // When serialized, this will use the uri value directly as the IRI
}

// A class that requires custom IRI construction logic
// Requires a custom mapper to be provided at runtime
@RdfIri.namedMapper('userReferenceMapper')
class UserReference {
  final String username;

  UserReference(this.username);
}

// This represents a custom mapper implementation for UserProfile that needs
// to be provided by the developer at runtime.
class UserReferenceMapper implements IriTermMapper<UserReference> {
  final String baseUrl;

  UserReferenceMapper({required this.baseUrl});

  @override
  IriTerm toRdfTerm(UserReference value, SerializationContext context) {
    return IriTerm('$baseUrl/users/${value.username}');
  }

  @override
  UserReference fromRdfTerm(IriTerm term, DeserializationContext context) {
    final uri = Uri.parse(term.iri);
    final segments = uri.pathSegments;

    if (segments.length >= 2 && segments[0] == 'users') {
      final username = segments[1];
      return UserReference(username);
    }

    throw FormatException('Invalid UserProfile IRI format: ${term.iri}');
  }
}

// -- Resource Iri --

// A resource class with static IRI construction from template
@RdfGlobalResource(
  SchemaBook.classIri,
  IriStrategy('https://library.example.org/books/{id}.ttl'),
)
class SimpleBook {
  // ID will be extracted from: https://library.example.org/books/{id}.ttl,
  // where {id} is the value of this field - e.g., 'hobbit'
  @RdfIriPart()
  final String id;

  @RdfProperty(SchemaBook.name)
  final String title;

  SimpleBook(this.id, this.title);
}

// A resource class with the IRI as Id property.
@RdfGlobalResource(SchemaPerson.classIri, IriStrategy())
class Person {
  // The field will contain the full IRI as Id, e.g.: https://example.org/person/43
  @RdfIriPart()
  final String iri;

  @RdfProperty(SchemaPerson.givenName)
  final String givenName;

  Person(this.iri, this.givenName);
}

// A resource class with multi-field ID mapping
@RdfGlobalResource(
  SchemaChapter.classIri,
  // Note: just using a template here would be most simple and convenient
  // RdfIri('https://example.org/books/{bookId}/chapters/{chapterId}'),
  //
  // but we want to demonstrate the use of a custom mapper. Note that
  // we allow mapping multiple parts of the IRI to different fields and the
  // mapper will be an IriTermMapper, but for a record type with all fields
  // annotated with `@RdfIriPart.position()`.
  IriStrategy.namedMapper('chapterIdMapper'),
)
class Chapter {
  // Note that you can use both @RdfIriPart and @RdfProperty annotations on the same field.
  // This is useful if one or more RDF Properties are Predicates in their own rights,
  // but also used for Iri construction.
  @RdfIriPart.position(1)
  @RdfProperty(SchemaChapter.isPartOf)
  final String bookId;

  // Note the use of position to specify the order of the IRI parts - this is important
  // since it controls the position in the record type used for the IriTermMapper.
  @RdfIriPart.position(2)
  @RdfProperty(SchemaChapter.position)
  final int chapterNumber;

  @RdfProperty(SchemaChapter.name)
  final String title;

  Chapter(this.bookId, this.chapterNumber, this.title);
}

// This represents a custom mapper implementation for the IRI of the Chapter class
class ChapterIdMapper implements IriTermMapper<(String bookId, int chapterId)> {
  final String baseUrl;

  ChapterIdMapper({required this.baseUrl});

  @override
  (String, int) fromRdfTerm(IriTerm term, DeserializationContext context) {
    final uri = Uri.parse(term.iri);
    final segments = uri.pathSegments;

    // Expected path: /books/{bookId}/chapters/{chapterId}
    if (segments.length >= 4 &&
        segments[0] == 'books' &&
        segments[2] == 'chapters') {
      var bookId = segments[1];
      var chapterId = int.parse(segments[3]);
      return (bookId, chapterId);
    }

    throw FormatException('Invalid Chapter/Section IRI format: ${term.iri}');
  }

  @override
  IriTerm toRdfTerm(
    (String bookId, int chapterNumber) value,
    SerializationContext context,
  ) {
    return IriTerm('$baseUrl/books/${value.$1}/chapters/${value.$2}');
  }
}

// -- generated code --

// all those mappers ...

// This would also be generated by the code generator
void initRdfMapper({
  required IriTermMapper<UserReference> userReferenceMapper,
  required IriTermMapper<(String bookId, int chapterId)> chapterIdMapper,
}) {
  // Register the custom mappers with the RDF mapper system
  print('Registering UserReferenceMapper: $userReferenceMapper');
  print('Registering SectionIdMapper: $chapterIdMapper');

  // In a real implementation, these would be registered with a mapper registry
  // ...
}

// -- Back to your code --

// Example usage
void main() {
  // Initialize the mapper system with our custom mappers
  final baseUrl = 'https://example.org';

  initRdfMapper(
    userReferenceMapper: UserReferenceMapper(baseUrl: baseUrl),
    chapterIdMapper: ChapterIdMapper(baseUrl: baseUrl),
  );

  // Create sample data
  final isbn = StandardIsbn('9780261102217');
  final uri = AbsoluteUri('https://example.org/resources/123');
  final user = UserReference('johndoe');
  final book = SimpleBook('hobbit', 'The Hobbit');
  final chapter = Chapter('hobbit', 3, 'Riddles in the Dark');

  // Example IRIs that would be generated
  print('ISBN IRI: ${isbn.value} => urn:isbn:9780261102217');
  print('Absolute URI: ${uri.uri} => https://example.org/resources/123');
  print(
    'User Profile IRI: ${user.username} => https://example.org/users/johndoe',
  );
  print('Book IRI: ${book.id} => https://library.example.org/books/hobbit');
  print(
    'Chapter IRI: ${chapter.chapterNumber} => https://example.org/books/hobbit/chapters/3/sections/riddles',
  );
}
