// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// This file was generated by the RDF Mapper Generator.
// Source: test/fixtures/local_resource_processor_test_models.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values

import 'package:rdf_core/rdf_core.dart';
import 'package:rdf_mapper/rdf_mapper.dart';

// Other imports
import 'local_resource_processor_test_models.dart';
import 'package:rdf_vocabularies/schema.dart' as schema;

/// Generated mapper for [Book] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type Book.
class BookMapper implements LocalResourceMapper<Book> {


  /// Constructor
  const BookMapper();

  @override
  IriTerm? get typeIri => schema.SchemaBook.classIri;

  @override
  Book fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String isbn = reader.require(schema.SchemaBook.isbn);
    final String title = reader.require(schema.SchemaBook.name);
    final String authorId = reader.require(schema.SchemaBook.author);

    final retval = Book(
      isbn: isbn,
      title: title,
      authorId: authorId
    );
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    Book resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValue(schema.SchemaBook.isbn, resource.isbn)
      .addValue(schema.SchemaBook.name, resource.title)
      .addValue(schema.SchemaBook.author, resource.authorId)
      .build();
  }

}


/// Generated mapper for [ClassNoRegisterGlobally] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type ClassNoRegisterGlobally.
class ClassNoRegisterGloballyMapper implements LocalResourceMapper<ClassNoRegisterGlobally> {


  /// Constructor
  const ClassNoRegisterGloballyMapper();

  @override
  IriTerm? get typeIri => schema.SchemaPerson.classIri;

  @override
  ClassNoRegisterGlobally fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String name = reader.require(schema.SchemaPerson.name);

    final retval = ClassNoRegisterGlobally(
      name: name
    );
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    ClassNoRegisterGlobally resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValue(schema.SchemaPerson.name, resource.name)
      .build();
  }

}


/// Generated mapper for [ClassWithNoRdfType] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type ClassWithNoRdfType.
class ClassWithNoRdfTypeMapper implements LocalResourceMapper<ClassWithNoRdfType> {


  /// Constructor
  const ClassWithNoRdfTypeMapper();

  @override
  IriTerm? get typeIri => null;

  @override
  ClassWithNoRdfType fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String name = reader.require(schema.SchemaPerson.name);
    final int age = reader.require(schema.SchemaPerson.foafAge);

    final retval = ClassWithNoRdfType(
      name,
      age: age
    );
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    ClassWithNoRdfType resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValue(schema.SchemaPerson.name, resource.name)
      .addValue(schema.SchemaPerson.foafAge, resource.age)
      .build();
  }

}


/// Generated mapper for [ClassWithPositionalProperty] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type ClassWithPositionalProperty.
class ClassWithPositionalPropertyMapper implements LocalResourceMapper<ClassWithPositionalProperty> {


  /// Constructor
  const ClassWithPositionalPropertyMapper();

  @override
  IriTerm? get typeIri => schema.SchemaPerson.classIri;

  @override
  ClassWithPositionalProperty fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String name = reader.require(schema.SchemaPerson.name);

    final retval = ClassWithPositionalProperty(
      name
    );
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    ClassWithPositionalProperty resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValue(schema.SchemaPerson.name, resource.name)
      .build();
  }

}


/// Generated mapper for [ClassWithNonFinalProperty] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type ClassWithNonFinalProperty.
class ClassWithNonFinalPropertyMapper implements LocalResourceMapper<ClassWithNonFinalProperty> {


  /// Constructor
  const ClassWithNonFinalPropertyMapper();

  @override
  IriTerm? get typeIri => schema.SchemaPerson.classIri;

  @override
  ClassWithNonFinalProperty fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String name = reader.require(schema.SchemaPerson.name);

    final retval = ClassWithNonFinalProperty(
      name: name
    );
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    ClassWithNonFinalProperty resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValue(schema.SchemaPerson.name, resource.name)
      .build();
  }

}


/// Generated mapper for [ClassWithNonFinalPropertyWithDefault] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type ClassWithNonFinalPropertyWithDefault.
class ClassWithNonFinalPropertyWithDefaultMapper implements LocalResourceMapper<ClassWithNonFinalPropertyWithDefault> {


  /// Constructor
  const ClassWithNonFinalPropertyWithDefaultMapper();

  @override
  IriTerm? get typeIri => schema.SchemaPerson.classIri;

  @override
  ClassWithNonFinalPropertyWithDefault fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String name = reader.require(schema.SchemaPerson.name);

    final retval = ClassWithNonFinalPropertyWithDefault(
    );
    retval.name = name;
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    ClassWithNonFinalPropertyWithDefault resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValue(schema.SchemaPerson.name, resource.name)
      .build();
  }

}


/// Generated mapper for [ClassWithNonFinalOptionalProperty] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type ClassWithNonFinalOptionalProperty.
class ClassWithNonFinalOptionalPropertyMapper implements LocalResourceMapper<ClassWithNonFinalOptionalProperty> {


  /// Constructor
  const ClassWithNonFinalOptionalPropertyMapper();

  @override
  IriTerm? get typeIri => schema.SchemaPerson.classIri;

  @override
  ClassWithNonFinalOptionalProperty fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String? name = reader.optional(schema.SchemaPerson.name);

    final retval = ClassWithNonFinalOptionalProperty(
    );
    retval.name = name;
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    ClassWithNonFinalOptionalProperty resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValueIfNotNull(schema.SchemaPerson.name, resource.name)
      .build();
  }

}


/// Generated mapper for [ClassWithLateNonFinalProperty] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type ClassWithLateNonFinalProperty.
class ClassWithLateNonFinalPropertyMapper implements LocalResourceMapper<ClassWithLateNonFinalProperty> {


  /// Constructor
  const ClassWithLateNonFinalPropertyMapper();

  @override
  IriTerm? get typeIri => schema.SchemaPerson.classIri;

  @override
  ClassWithLateNonFinalProperty fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String name = reader.require(schema.SchemaPerson.name);

    final retval = ClassWithLateNonFinalProperty(
    );
    retval.name = name;
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    ClassWithLateNonFinalProperty resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValue(schema.SchemaPerson.name, resource.name)
      .build();
  }

}


/// Generated mapper for [ClassWithLateFinalProperty] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type ClassWithLateFinalProperty.
class ClassWithLateFinalPropertyMapper implements LocalResourceMapper<ClassWithLateFinalProperty> {


  /// Constructor
  const ClassWithLateFinalPropertyMapper();

  @override
  IriTerm? get typeIri => schema.SchemaPerson.classIri;

  @override
  ClassWithLateFinalProperty fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String name = reader.require(schema.SchemaPerson.name);

    final retval = ClassWithLateFinalProperty(
    );
    retval.name = name;
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    ClassWithLateFinalProperty resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValue(schema.SchemaPerson.name, resource.name)
      .build();
  }

}


/// Generated mapper for [ClassWithMixedFinalAndLateFinalProperty] global resources.
/// 
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type ClassWithMixedFinalAndLateFinalProperty.
class ClassWithMixedFinalAndLateFinalPropertyMapper implements LocalResourceMapper<ClassWithMixedFinalAndLateFinalProperty> {


  /// Constructor
  const ClassWithMixedFinalAndLateFinalPropertyMapper();

  @override
  IriTerm? get typeIri => schema.SchemaPerson.classIri;

  @override
  ClassWithMixedFinalAndLateFinalProperty fromRdfResource(BlankNodeTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);
    

    
    final String name = reader.require(schema.SchemaPerson.name);
    final int age = reader.require(schema.SchemaPerson.foafAge);

    final retval = ClassWithMixedFinalAndLateFinalProperty(
      name: name
    );
    retval.age = age;
    return retval;
  }

  @override
  (BlankNodeTerm, List<Triple>) toRdfResource(
    ClassWithMixedFinalAndLateFinalProperty resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();
    
    return context.resourceBuilder(subject)
      .addValue(schema.SchemaPerson.name, resource.name)
      .addValue(schema.SchemaPerson.foafAge, resource.age)
      .build();
  }

}


